### ISSUE TITLE
wept是否支持linux运行？

### ISSUE THREAD

**Issue by smallsong** [wetools/wept#133]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
wept-1    | listening on port 3108
wept-1    | Error: Command failed: wine /usr/local/lib/node_modules/wept/bin/wcsc.exe -lc -db ./pages/index/index.wxss
wept-1    | /bin/sh: 1: wine: not found
wept-1    |
wept-1    |     at ChildProcess.exithandler (child_process.js:303:12)
wept-1    |     at ChildProcess.emit (events.js:315:20)
wept-1    |     at maybeClose (internal/child_process.js:1021:16)
wept-1    |     at Socket.<anonymous> (internal/child_process.js:443:11)
wept-1    |     at Socket.emit (events.js:315:20)
wept-1    |     at Pipe.<anonymous> (net.js:674:12)
wept-1    | Error: pages/index/index.wxss 编译失败，请检查
wept-1    |     at /usr/local/lib/node_modules/wept/build/parser.js:79:27
wept-1    |     at ChildProcess.exithandler (child_process.js:310:5)
wept-1    |     at ChildProcess.emit (events.js:315:20)
wept-1    |     at maybeClose (internal/child_process.js:1021:16)
wept-1    |     at Socket.<anonymous> (internal/child_process.js:443:11)
wept-1    |     at Socket.emit (events.js:315:20)
wept-1    |     at Pipe.<anonymous> (net.js:674:12)
wept-1    | pages/index/index.wxss 编译失败，请检查
wept-1    | An error occured. Error: spawn notify-send ENOENT
wept-1    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
wept-1    |     at onErrorNT (internal/child_process.js:469:16)
wept-1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
wept-1    |   errno: 'ENOENT',
wept-1    |   code: 'ENOENT',
wept-1    |   syscall: 'spawn notify-send',
wept-1    |   path: 'notify-send',
wept-1    |   spawnargs: [
wept-1    |     '-i',
wept-1    |     '/usr/local/lib/node_modules/wept/public/images/error.png',
wept-1    |     '--hint=int:transient:1',
wept-1    |     'pages/index/index.wxss 编译失败，请检查'
wept-1    |   ]
wept-1    | }
wept-1    | Error: Command failed: wine /usr/local/lib/node_modules/wept/bin/wcc.exe -d ./pages/index/index.wxml
wept-1    | /bin/sh: 1: wine: not found
wept-1    |
wept-1    |     at ChildProcess.exithandler (child_process.js:303:12)
wept-1    |     at ChildProcess.emit (events.js:315:20)
wept-1    |     at maybeClose (internal/child_process.js:1021:16)
wept-1    |     at Socket.<anonymous> (internal/child_process.js:443:11)
wept-1    |     at Socket.emit (events.js:315:20)
wept-1    |     at Pipe.<anonymous> (net.js:674:12)
wept-1    | pages/index/index.wxml 编译失败，请检查
wept-1    | Error: pages/index/index.wxml 编译失败，请检查
wept-1    |     at /usr/local/lib/node_modules/wept/build/parser.js:61:27
wept-1    |     at ChildProcess.exithandler (child_process.js:310:5)
wept-1    |     at ChildProcess.emit (events.js:315:20)
wept-1    |     at maybeClose (internal/child_process.js:1021:16)
wept-1    |     at Socket.<anonymous> (internal/child_process.js:443:11)
wept-1    |     at Socket.emit (events.js:315:20)
wept-1    |     at Pipe.<anonymous> (net.js:674:12)
wept-1    | An error occured. Error: spawn notify-send ENOENT
wept-1    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
wept-1    |     at onErrorNT (internal/child_process.js:469:16)
wept-1    |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
wept-1    |   errno: 'ENOENT',
wept-1    |   code: 'ENOENT',
wept-1    |   syscall: 'spawn notify-send',
wept-1    |   path: 'notify-send',
wept-1    |   spawnargs: [
wept-1    |     '-i',
wept-1    |     '/usr/local/lib/node_modules/wept/public/images/error.png',
wept-1    |     '--hint=int:transient:1',
wept-1    |     'pages/index/index.wxml 编译失败，请检查'
wept-1    |   ]
wept-1    | }
wept-1    |  ✓ service.js build success

**Comment by sleepm** [comment]
需要wine还有wine-mono
然后遇到了fixme:font:get_name_record_codepage encoding 29 not handled, platform 1，搜了下说是mesa需要降级
直接放弃了

**Comment by suntong** [comment]
wept Readme 说支持linux运行

我就是冲这个来的，结果

> 需要wine还有wine-mono

就冲这个我也直接放弃了
